import Link from "next/link";
import { redirect } from "next/navigation";
import { BrandMark, Icon } from "@/components/icons";
import { requireCustomerSession } from "@/lib/auth/session";
import { getCustomerPortal } from "@/lib/api/autoservice-api";
import { formatRub, visitStatusMeta } from "@/lib/domain";

export const metadata = { title: "Мой автомобиль" };

export default async function CustomerCabinetPage({ searchParams }: { searchParams: Promise<{ approval?: string }> }) {
  const session = await requireCustomerSession();
  const portal = await getCustomerPortal(session);
  if (!portal) redirect("/customer/login?error=invalid_credentials");
  const { approval } = await searchParams;
  return <main className="customer-page"><header className="customer-header"><BrandMark />{portal.workshop.phone && <a href={`tel:${portal.workshop.phone.replace(/[^+\d]/g, "")}`}><Icon name="phone" /> {portal.workshop.phone}</a>}</header><div className="customer-shell"><section className="customer-intro"><span className="eyebrow">{portal.workshop.name}</span><h1>Здравствуйте, {portal.customer.name}</h1><p>Здесь собраны ваши автомобили, текущие работы и история обращений.</p></section>{approval && <p className="admin-notice admin-notice-success">Ссылка согласования открыта. Нужная работа показана в составе соответствующего ремонта ниже.</p>}<section className="content-card" style={{ padding: 24, marginBottom: 22 }}><h2>Мои автомобили</h2><div className="attention-list">{portal.vehicles.length ? portal.vehicles.map((vehicle) => <div className="attention-card" key={vehicle.id}><span className="vehicle-icon"><Icon name="car" /></span><div className="attention-copy"><strong>{vehicle.label}</strong><small>{vehicle.licensePlate || "Госномер не указан"}</small></div></div>) : <p className="muted">Автомобили появятся после первой заявки.</p>}</div></section><section><div className="section-heading"><div><h2>Мои ремонты</h2><p>Текущие и завершённые обращения</p></div></div><div className="attention-list">{portal.visits.map((visit) => { const status = visitStatusMeta[visit.status]; const total = visit.findings.filter((finding) => finding.status === "APPROVED").reduce((sum, finding) => sum + (finding.priceRub ?? 0), 0); return <article className="content-card" style={{ padding: 20 }} key={visit.id}><div className="visit-header"><div className="visit-identity"><span className="vehicle-large"><Icon name="car" /></span><div><div className="title-line"><h2>{visit.vehicleLabel}</h2><span className={`status-pill status-${status.tone}`}>{status.label}</span></div><p>{visit.licensePlate} · {visit.complaint}</p></div></div></div><p className="muted">Работы: {visit.findings.length} · Материалы: {visit._count.media}{total ? ` · Согласовано: ${formatRub(total)}` : ""}</p>{visit.findings.length > 0 && <div className="finding-list">{visit.findings.map((finding) => <div className="finding-card" key={finding.id}><strong>{finding.title}</strong><p>{finding.description}</p><small>{finding.priceRub ? formatRub(finding.priceRub) : "Стоимость уточняется"} · {finding.status}</small></div>)}</div>}</article>; })}</div></section></div><footer className="customer-footer"><span>AutoService</span><p><Link href="/customer/login">Сменить аккаунт</Link></p></footer></main>;
}
