import type { Customer, Reminder, Visit } from "@/lib/domain";

export const visits: Visit[] = [
  {
    id: "visit-camry",
    vehicle: "Toyota Camry",
    plate: "А123АА 56",
    customer: "Иван Петров",
    phone: "+7 999 000-00-00",
    mileageKm: 120_450,
    complaint: "Стук спереди справа на неровностях",
    status: "WAITING_APPROVAL",
    syncHealth: "SYNCED",
    updatedAt: "12 мин назад",
    arrivedAt: "Сегодня, 09:20",
    mechanic: "Алексей",
    nextAction: "Позвонить клиенту",
    attention: "Клиент запросил звонок по тормозным колодкам",
    mediaCount: 8,
    findings: [
      {
        id: "finding-brakes",
        title: "Износ задних тормозных колодок",
        description:
          "Остаток фрикционного материала около 2 мм. Рекомендуем заменить колодки в этот визит.",
        priceRub: 12_800,
        priority: "CRITICAL",
        status: "CALL_REQUESTED",
        mediaCount: 3,
      },
      {
        id: "finding-link",
        title: "Люфт стойки стабилизатора",
        description:
          "Обнаружен люфт правой передней стойки. Из-за него появляется стук на неровностях.",
        priceRub: 6_400,
        priority: "IMPORTANT",
        status: "APPROVED",
        mediaCount: 2,
      },
      {
        id: "finding-filter",
        title: "Загрязнение салонного фильтра",
        description: "Можно заменить при следующем плановом обслуживании.",
        priceRub: 2_100,
        priority: "PLANNED",
        status: "DEFERRED",
        mediaCount: 1,
      },
    ],
    events: [
      { id: "e1", title: "Клиент запросил звонок", detail: "Задние тормозные колодки", time: "12:48", tone: "warning" },
      { id: "e2", title: "Работа согласована", detail: "Стойка стабилизатора · 6 400 ₽", time: "12:42", tone: "positive" },
      { id: "e3", title: "Согласование открыто", detail: "Клиент перешёл по ссылке", time: "12:39", tone: "neutral" },
      { id: "e4", title: "Диагностика завершена", detail: "Добавлено 3 находки и 6 материалов", time: "12:24", tone: "neutral" },
      { id: "e5", title: "Автомобиль принят", detail: "Пробег 120 450 км", time: "09:20", tone: "neutral" },
    ],
  },
  {
    id: "visit-solaris",
    vehicle: "Hyundai Solaris",
    plate: "К845МР 56",
    customer: "Мария Соколова",
    phone: "+7 912 555-28-10",
    mileageKm: 87_200,
    complaint: "Плановое ТО и проверка кондиционера",
    status: "IN_REPAIR",
    syncHealth: "SYNCING",
    updatedAt: "4 мин назад",
    arrivedAt: "Сегодня, 10:15",
    mechanic: "Дмитрий",
    nextAction: "Завершить диагностику",
    mediaCount: 5,
    findings: [
      {
        id: "finding-ac",
        title: "Недостаточное давление хладагента",
        description: "Нужна проверка герметичности контура кондиционера.",
        priceRub: 3_500,
        priority: "IMPORTANT",
        status: "DRAFT",
        mediaCount: 1,
      },
    ],
    events: [
      { id: "e1", title: "Добавлена находка", detail: "Недостаточное давление хладагента", time: "12:51", tone: "neutral" },
      { id: "e2", title: "Начат ремонт", detail: "Мастер Дмитрий", time: "10:32", tone: "neutral" },
      { id: "e3", title: "Автомобиль принят", detail: "Плановое ТО", time: "10:15", tone: "neutral" },
    ],
  },
  {
    id: "visit-lada",
    vehicle: "Lada Vesta",
    plate: "Т410ОВ 156",
    customer: "Сергей Волков",
    phone: "+7 922 143-71-02",
    mileageKm: 63_880,
    complaint: "Скрип при торможении",
    status: "DRAFT",
    syncHealth: "ATTENTION",
    updatedAt: "18 мин назад",
    arrivedAt: "Сегодня, 11:40",
    mechanic: "Не назначен",
    nextAction: "Начать ремонт",
    attention: "2 фотографии требуют повторной загрузки",
    mediaCount: 4,
    findings: [],
    events: [
      { id: "e1", title: "Ошибка загрузки", detail: "2 фотографии остались на телефоне", time: "12:37", tone: "warning" },
      { id: "e2", title: "Автомобиль принят", detail: "Скрип при торможении", time: "11:40", tone: "neutral" },
    ],
  },
  {
    id: "visit-kia",
    vehicle: "Kia Rio",
    plate: "О917НС 56",
    customer: "Ольга Морозова",
    phone: "+7 987 330-42-11",
    mileageKm: 102_110,
    complaint: "Замена масла и фильтров",
    status: "IN_REPAIR",
    syncHealth: "SYNCED",
    updatedAt: "31 мин назад",
    arrivedAt: "Сегодня, 08:45",
    mechanic: "Алексей",
    nextAction: "Подготовить отчёт",
    mediaCount: 6,
    findings: [],
    events: [
      { id: "e1", title: "Работы выполнены", detail: "Масло и фильтры заменены", time: "12:10", tone: "positive" },
      { id: "e2", title: "Начат ремонт", detail: "Мастер Алексей", time: "09:05", tone: "neutral" },
    ],
  },
  {
    id: "visit-skoda",
    vehicle: "Skoda Octavia",
    plate: "Е531СК 56",
    customer: "Андрей Орлов",
    phone: "+7 905 618-09-44",
    mileageKm: 145_700,
    complaint: "Диагностика подвески",
    status: "COMPLETED",
    syncHealth: "SYNCED",
    updatedAt: "вчера",
    arrivedAt: "Вчера, 13:10",
    mechanic: "Дмитрий",
    nextAction: "Нет действий",
    mediaCount: 9,
    findings: [
      {
        id: "finding-arm",
        title: "Износ сайлентблоков",
        description: "Работы выполнены после согласования с клиентом.",
        priceRub: 18_600,
        priority: "IMPORTANT",
        status: "APPROVED",
        mediaCount: 4,
      },
    ],
    events: [
      { id: "e1", title: "Отчёт опубликован", detail: "Клиенту отправлена ссылка", time: "Вчера, 18:22", tone: "positive" },
    ],
  },
];

export const customers: Customer[] = [
  { id: "customer-ivan", name: "Иван Петров", phone: "+7 999 000-00-00", vehicles: ["Toyota Camry · А123АА 56"], visitsCount: 4, lastVisit: "Сегодня" },
  { id: "customer-maria", name: "Мария Соколова", phone: "+7 912 555-28-10", vehicles: ["Hyundai Solaris · К845МР 56"], visitsCount: 2, lastVisit: "Сегодня", nextContact: "ТО через 8 000 км" },
  { id: "customer-sergey", name: "Сергей Волков", phone: "+7 922 143-71-02", vehicles: ["Lada Vesta · Т410ОВ 156"], visitsCount: 1, lastVisit: "Сегодня" },
  { id: "customer-olga", name: "Ольга Морозова", phone: "+7 987 330-42-11", vehicles: ["Kia Rio · О917НС 56"], visitsCount: 3, lastVisit: "Сегодня", nextContact: "Замена масла · 14 декабря" },
  { id: "customer-andrey", name: "Андрей Орлов", phone: "+7 905 618-09-44", vehicles: ["Skoda Octavia · Е531СК 56"], visitsCount: 6, lastVisit: "11 сентября", nextContact: "Проверка подвески · 10 ноября" },
];

export const reminders: Reminder[] = [
  { id: "r1", customer: "Николай Котов", vehicle: "Renault Duster", reason: "Замена масла", due: "Просрочено на 3 дня", state: "OVERDUE" },
  { id: "r2", customer: "Анна Лебедева", vehicle: "Volkswagen Polo", reason: "Проверка тормозов", due: "Сегодня", state: "TODAY" },
  { id: "r3", customer: "Андрей Орлов", vehicle: "Skoda Octavia", reason: "Проверка подвески", due: "10 ноября", state: "UPCOMING" },
  { id: "r4", customer: "Ольга Морозова", vehicle: "Kia Rio", reason: "Замена масла", due: "14 декабря", state: "UPCOMING" },
];
